# Codecov 配置文件
# 参考文档: https://docs.codecov.com/docs/codecov-yaml

# 覆盖率设置
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 70%
        threshold: 1%
        informational: false

# 注释设置
comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# 忽略的路径
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/coverage/**"
  - "*.config.*"
  - "*.setup.*"
  - "electron/**"
  - "src/main.tsx"
